name: GangsPlugin
main: com.emirhan.gangs.GangsPlugin
version: 1.1.0
api-version: 1.16
author: Emirhan
softdepend:
  - PlaceholderAPI

commands:
  cete:
    description: Çete komutu
    usage: /cete yardım
    aliases: [gang, gangs]

permissions:
  cete.admin:
    description: Çete admin yetkisi
    default: op
